FROM ghcr.io/astral-sh/uv:python3.14-trixie AS builder
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_NO_DEV=1
ENV UV_PYTHON_DOWNLOADS=0
WORKDIR /app

RUN --mount=type=cache,id=s/201c4983-6333-4eed-8b1a-92688f29c823-/root/cache/uv,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

COPY . /app

RUN --mount=type=cache,id=s/201c4983-6333-4eed-8b1a-92688f29c823-/root/cache/uv,target=/root/.cache/uv \
    uv sync --locked --no-editable

FROM python:3.14-slim-trixie
RUN groupadd --system --gid 999 nonroot \
    && useradd --system --gid 999 --uid 999 --create-home nonroot
WORKDIR /app
COPY --from=builder --chown=nonroot:nonroot /app /app
ENV PATH="/app/.venv/bin:$PATH"
RUN chmod +x /app/scripts/entrypoint.sh
USER nonroot
CMD ["/app/scripts/entrypoint.sh"]