"""add_warehouse_pickup_fields

Revision ID: 8e058e9a7678
Revises: a1b2c3d4e5f6
Create Date: 2026-03-27 20:46:42.856501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e058e9a7678'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new enum values to native PostgreSQL enums
    op.execute("ALTER TYPE order_status_enum ADD VALUE IF NOT EXISTS 'pickup_completed'")
    op.execute("ALTER TYPE transfer_type_enum ADD VALUE IF NOT EXISTS 'WAREHOUSE_SALE'")
    op.execute("ALTER TYPE transfer_type_enum ADD VALUE IF NOT EXISTS 'WAREHOUSE_TARA_RETURN'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sale_type', sa.String(length=30), server_default='delivery', nullable=False, comment='Тип продажи: delivery (доставка) или warehouse_pickup (самовывоз)'))
    op.add_column('orders', sa.Column('warehouse_id', sa.UUID(), nullable=True, comment='Склад-источник (заполняется только для самовывоза)'))
    op.create_index(op.f('ix_orders_sale_type'), 'orders', ['sale_type'], unique=False)
    op.create_index(op.f('ix_orders_warehouse_id'), 'orders', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'inventories', ['warehouse_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Note: PostgreSQL does not support removing enum values.
    # 'pickup_completed', 'WAREHOUSE_SALE', 'WAREHOUSE_TARA_RETURN' will remain in their enums.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_warehouse_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_sale_type'), table_name='orders')
    op.drop_column('orders', 'warehouse_id')
    op.drop_column('orders', 'sale_type')
    # ### end Alembic commands ###
