"""add_new_models_and_columns

Revision ID: aec319431748
Revises: cf2a824cf0fb
Create Date: 2026-03-04 05:10:08.015445

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aec319431748"
down_revision: Union[str, Sequence[str], None] = "cf2a824cf0fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_transfers",
        sa.Column(
            "type",
            sa.Enum(
                "FACTORY_RECEIPT",
                "PURCHASE",
                "PRODUCTION",
                "COURIER_LOAD",
                "COURIER_RETURN",
                "CLIENT_DELIVERY",
                "CLIENT_RETURN",
                "WAREHOUSE_TRANSFER",
                "LOSS_WRITE_OFF",
                "INVENTORY_FINDING",
                name="transfer_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "COMPLETED",
                "CANCELLED",
                name="transfer_status_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("from_id", sa.UUID(), nullable=False),
        sa.Column("to_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("accepted_by_id", sa.UUID(), nullable=True),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint(
            "from_id != to_id", name="ck_stock_transfer_no_circular"
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["from_id"], ["inventories.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["to_id"], ["inventories.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id", "from_id", "to_id", name="uq_stock_transfer_route"
        ),
    )
    op.create_index(
        op.f("ix_stock_transfers_from_id"),
        "stock_transfers",
        ["from_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_order_id"),
        "stock_transfers",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_status"),
        "stock_transfers",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_to_id"),
        "stock_transfers",
        ["to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_type"),
        "stock_transfers",
        ["type"],
        unique=False,
    )
    op.create_table(
        "stock_transfer_items",
        sa.Column("transfer_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint(
            "quantity > 0", name="ck_stock_transfer_item_quantity_pos"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"], ["stock_transfers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_transfer_items_product_id"),
        "stock_transfer_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfer_items_transfer_id"),
        "stock_transfer_items",
        ["transfer_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_transfers_from_inventory_id"), table_name="transfers"
    )
    op.drop_index(op.f("ix_transfers_number"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_to_inventory_id"), table_name="transfers")
    op.execute("DROP TABLE IF EXISTS transfers CASCADE;")
    op.drop_index(
        op.f("idx_transfer_product_unique"), table_name="transfer_items"
    )
    op.drop_index(
        op.f("ix_transfer_items_transfer_id"), table_name="transfer_items"
    )
    op.drop_table("transfer_items")
    op.alter_column(
        "inventories",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Например: 'Склад №1', 'Машина Дамас 01A123BC'",
        existing_nullable=False,
    )
    op.add_column(
        "orders",
        sa.Column(
            "client_inventory_id",
            sa.UUID(),
            nullable=False,
            comment="Инвентарь (адрес) клиента",
        ),
    )
    op.create_index(
        op.f("ix_orders_client_inventory_id"),
        "orders",
        ["client_inventory_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "orders",
        "inventories",
        ["client_inventory_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "products",
        "attributes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "stock_transactions",
        "transfer_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_index(
        op.f("ix_stock_transactions_order_id"), table_name="stock_transactions"
    )
    op.drop_constraint(
        op.f("stock_transactions_order_id_fkey"),
        "stock_transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_stock_transaction_strict_route",
        "stock_transactions",
        "stock_transfers",
        ["transfer_id", "from_id", "to_id"],
        ["id", "from_id", "to_id"],
        ondelete="CASCADE",
    )
    op.drop_column("stock_transactions", "order_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_transactions",
        sa.Column("order_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "fk_stock_transaction_strict_route",
        "stock_transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("stock_transactions_transfer_id_fkey"),
        "stock_transactions",
        "transfers",
        ["transfer_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("stock_transactions_order_id_fkey"),
        "stock_transactions",
        "orders",
        ["order_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_stock_transactions_order_id"),
        "stock_transactions",
        ["order_id"],
        unique=False,
    )
    op.alter_column(
        "stock_transactions",
        "transfer_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "products",
        "attributes",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_constraint(None, "orders", type_="foreignkey")  # ty:ignore[invalid-argument-type]
    op.drop_index(op.f("ix_orders_client_inventory_id"), table_name="orders")
    op.drop_column("orders", "client_inventory_id")
    op.alter_column(
        "inventories",
        "name",
        existing_type=sa.VARCHAR(length=255),
        comment="Например: 'Склад №1', 'Машина Дамас 01A123BC'",
        existing_nullable=False,
    )
    op.create_table(
        "transfer_items",
        sa.Column(
            "transfer_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "product_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="ID (UUIDv7)",
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("transfer_items_product_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["transfers.id"],
            name=op.f("transfer_items_transfer_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transfer_items_pkey")),
    )
    op.create_index(
        op.f("ix_transfer_items_transfer_id"),
        "transfer_items",
        ["transfer_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_transfer_product_unique"),
        "transfer_items",
        ["transfer_id", "product_id"],
        unique=True,
    )
    op.create_table(
        "transfers",
        sa.Column("number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "from_inventory_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "to_inventory_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "initiator_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT",
                "COMPLETED",
                "CANCELLED",
                name="transfer_status_enum",
                metadata=MetaData(),
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="ID (UUIDv7)",
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint(
            "from_inventory_id <> to_inventory_id",
            name=op.f("check_transfer_different_inventories"),
        ),
        sa.ForeignKeyConstraint(
            ["from_inventory_id"],
            ["inventories.id"],
            name=op.f("transfers_from_inventory_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initiator_id"],
            ["users.id"],
            name=op.f("transfers_initiator_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_inventory_id"],
            ["inventories.id"],
            name=op.f("transfers_to_inventory_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transfers_pkey")),
    )
    op.create_index(
        op.f("ix_transfers_to_inventory_id"),
        "transfers",
        ["to_inventory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transfers_status"), "transfers", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_number"), "transfers", ["number"], unique=True
    )
    op.create_index(
        op.f("ix_transfers_from_inventory_id"),
        "transfers",
        ["from_inventory_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_stock_transfer_items_transfer_id"),
        table_name="stock_transfer_items",
    )
    op.drop_index(
        op.f("ix_stock_transfer_items_product_id"),
        table_name="stock_transfer_items",
    )
    op.drop_table("stock_transfer_items")
    op.drop_index(
        op.f("ix_stock_transfers_type"), table_name="stock_transfers"
    )
    op.drop_index(
        op.f("ix_stock_transfers_to_id"), table_name="stock_transfers"
    )
    op.drop_index(
        op.f("ix_stock_transfers_status"), table_name="stock_transfers"
    )
    op.drop_index(
        op.f("ix_stock_transfers_order_id"), table_name="stock_transfers"
    )
    op.drop_index(
        op.f("ix_stock_transfers_from_id"), table_name="stock_transfers"
    )
    op.drop_table("stock_transfers")
    # ### end Alembic commands ###
