"""init

Revision ID: cefde77d7774
Revises:
Create Date: 2026-03-27 22:58:49.095144

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cefde77d7774"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column(
            "returnable_item_id",
            sa.UUID(),
            nullable=True,
            comment="Ссылка на оборотную тару (например, пустая бутыль 19л, привязанная к воде)",
        ),
        sa.Column(
            "type",
            sa.Enum(
                "WATER",
                "CONTAINER",
                "EQUIPMENT",
                name="product_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Категория продукта (WATER, EQUIPMENT, CONTAINER)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Витринное название товара",
        ),
        sa.Column(
            "price", sa.BIGINT(), nullable=False, comment="Базовая стоимость товара"
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Динамические характеристики (объем, бренд, цвет, мощность)",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint("price >= 0", name="ck_product_price_pos"),
        sa.ForeignKeyConstraint(
            ["returnable_item_id"], ["products.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Единый каталог товаров, услуг и оборотной тары",
    )
    op.create_index(
        "idx_product_attributes_gin",
        "products",
        ["attributes"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_products_returnable_item_id"),
        "products",
        ["returnable_item_id"],
        unique=False,
    )
    op.create_index(op.f("ix_products_type"), "products", ["type"], unique=False)
    op.create_table(
        "users",
        sa.Column(
            "username",
            sa.String(length=255),
            nullable=False,
            comment="ФИО (для физлиц) или Название компании (для B2B)",
        ),
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM",
                "ADMIN",
                "ACCOUNTANT",
                "STOREKEEPER",
                "CASHIER",
                "COURIER",
                "CLIENT_B2C",
                "CLIENT_B2B",
                name="user_role_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Уровень доступа (роль) пользователя в системе",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Глобальный реестр пользователей, клиентов и сотрудников",
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="Владелец счета"),
        sa.Column(
            "type",
            sa.Enum(
                "REVENUE",
                "CASH",
                "CARD",
                "BANK",
                "DISCOUNT",
                "CLIENT",
                "COURIER",
                name="account_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Тип счета (CASH, CARD, DEBT, COMPANY_PROFIT)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Название (например: 'Касса Водителя', 'Лицевой счет')",
        ),
        sa.Column(
            "balance",
            sa.BIGINT(),
            nullable=False,
            comment="Текущий баланс. Обновляется строго через SQL-триггер транзакций!",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        comment="Счета для хранения денег (наличные, безнал, долги клиентов)",
    )
    op.create_index(
        "idx_account_user_type", "accounts", ["user_id", "type"], unique=False
    )
    op.create_index(op.f("ix_accounts_type"), "accounts", ["type"], unique=False)
    op.create_table(
        "identities",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Ссылка на профиль пользователя",
        ),
        sa.Column(
            "provider",
            sa.Enum(
                "LOCAL",
                "GOOGLE",
                "TELEGRAM",
                "APPLE",
                name="auth_provider_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Провайдер авторизации (local, google, telegram и т.д.)",
        ),
        sa.Column(
            "provider_identity_id",
            sa.String(length=255),
            nullable=False,
            comment="Уникальный ID у провайдера: номер телефона, email или субъект (sub) из OAuth",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=True,
            comment="Хэш пароля (заполняется только для provider='local')",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "provider_identity_id",
            name="uq_identities_provider_identity_id",
        ),
        comment="Учетные данные пользователей и привязки к соцсетям (OAuth)",
    )
    op.create_index(
        op.f("ix_identities_user_id"), "identities", ["user_id"], unique=False
    )
    op.create_table(
        "inventories",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Кто материально ответственен за эту точку (курьер, клиент, кладовщик)?",
        ),
        sa.Column(
            "type",
            sa.Enum(
                "WAREHOUSE",
                "COURIER",
                "CLIENT",
                "VIRTUAL_LOSS",
                "VIRTUAL_VENDOR",
                name="inventory_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Тип инвентаря: WAREHOUSE, COURIER, CLIENT, VIRTUAL",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Понятное название (например: 'Машина АВ123', 'Склад Центр')",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        comment="Реестр всех физических и виртуальных мест хранения (склады, машины, клиенты)",
    )
    op.create_index(
        "idx_inventory_user_type", "inventories", ["user_id", "type"], unique=False
    )
    op.create_index(op.f("ix_inventories_type"), "inventories", ["type"], unique=False)
    op.create_index(
        "uq_active_courier_inventory",
        "inventories",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("type = 'COURIER' AND is_active = true"),
    )
    op.create_table(
        "inventory_balances",
        sa.Column("inventory_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity", sa.Integer(), nullable=False, comment="Фактический остаток"
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["inventory_id"], ["inventories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "inventory_id", "product_id", name="uq_inventory_product_balance"
        ),
        comment="Материализованные (закэшированные) остатки. Обновляется триггером базы данных",
    )
    op.create_index(
        op.f("ix_inventory_balances_product_id"),
        "inventory_balances",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column(
            "client_id", sa.UUID(), nullable=False, comment="Покупатель (B2B или B2C)"
        ),
        sa.Column(
            "client_inventory_id",
            sa.UUID(),
            nullable=False,
            comment="Инвентарь (адрес) клиента для отгрузки товаров и тары",
        ),
        sa.Column(
            "courier_id",
            sa.UUID(),
            nullable=True,
            comment="Назначенный курьер (может быть пустым, пока заказ не взят в работу)",
        ),
        sa.Column(
            "payment_method",
            sa.Enum(
                "CASH",
                "CARD",
                "CONTRACT",
                name="payment_method_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Намерение клиента по оплате: Наличные, Карта и т.д.",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "ASSIGNED",
                "IN_TRANSIT",
                "ARRIVED",
                "DELIVERED",
                "PICKUP_COMPLETED",
                "CANCELLED",
                name="order_status_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Текущий статус жизненного цикла заказа",
        ),
        sa.Column(
            "total_amount", sa.BIGINT(), nullable=False, comment="Сумма всего заказа"
        ),
        sa.Column(
            "capitalization_applied",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Было ли авто-оприходование тары при создании заказа",
        ),
        sa.Column(
            "sale_type",
            sa.String(length=30),
            server_default="delivery",
            nullable=False,
            comment="Тип продажи: delivery (доставка) или warehouse_pickup (самовывоз)",
        ),
        sa.Column(
            "warehouse_id",
            sa.UUID(),
            nullable=True,
            comment="Склад-источник (заполняется только для самовывоза)",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(["client_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["client_inventory_id"], ["inventories.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["courier_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["inventories.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Главная таблица заказов клиентов",
    )
    op.create_index(op.f("ix_orders_client_id"), "orders", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_orders_client_inventory_id"),
        "orders",
        ["client_inventory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orders_courier_id"), "orders", ["courier_id"], unique=False
    )
    op.create_index(op.f("ix_orders_sale_type"), "orders", ["sale_type"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_orders_warehouse_id"), "orders", ["warehouse_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity", sa.INTEGER(), nullable=False, comment="Количество позиций"
        ),
        sa.Column(
            "unit_price",
            sa.BIGINT(),
            nullable=False,
            comment="Цена за 1 шт на момент оформления (фиксируется исторически)",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_order_item_quantity_pos"),
        sa.CheckConstraint("unit_price >= 0", name="ck_order_item_price_pos"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        comment="Строки (позиции) конкретного заказа",
    )
    op.create_index(
        op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_items_product_id"), "order_items", ["product_id"], unique=False
    )
    op.create_table(
        "stock_transfers",
        sa.Column("from_id", sa.UUID(), nullable=False),
        sa.Column("to_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_by_id",
            sa.UUID(),
            nullable=False,
            comment="Кто создал документ перемещения",
        ),
        sa.Column(
            "accepted_by_id",
            sa.UUID(),
            nullable=True,
            comment="Кто физически принял товар (подтвердил накладную)",
        ),
        sa.Column(
            "order_id",
            sa.UUID(),
            nullable=True,
            comment="Ссылка на клиентский заказ (если применимо)",
        ),
        sa.Column(
            "reason",
            sa.String(length=255),
            nullable=True,
            comment="Причина (для списания LOSS_WRITE_OFF)",
        ),
        sa.Column(
            "route_sheet_id",
            sa.UUID(),
            nullable=True,
            comment="ID маршрутного листа (для COURIER_LOAD)",
        ),
        sa.Column(
            "type",
            sa.Enum(
                "COURIER_LOAD",
                "COURIER_RETURN",
                "CLIENT_DELIVERY",
                "CLIENT_RETURN",
                "LOSS_WRITE_OFF",
                "INVENTORY_FINDING",
                "INITIAL_BALANCE",
                "WAREHOUSE_SALE",
                "WAREHOUSE_TARA_RETURN",
                name="transfer_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "COMPLETED",
                "CANCELLED",
                name="transfer_status_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Статус документа (DRAFT, COMPLETED, CANCELLED)",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint("from_id != to_id", name="ck_stock_transfer_no_circular"),
        sa.ForeignKeyConstraint(["accepted_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["from_id"], ["inventories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["to_id"], ["inventories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "from_id", "to_id", name="uq_stock_transfer_route"),
        comment="Документы (накладные) на перемещение товаров между складами/клиентами",
    )
    op.create_index(
        op.f("ix_stock_transfers_from_id"), "stock_transfers", ["from_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transfers_order_id"),
        "stock_transfers",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_route_sheet_id"),
        "stock_transfers",
        ["route_sheet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfers_status"), "stock_transfers", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transfers_to_id"), "stock_transfers", ["to_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transfers_type"), "stock_transfers", ["type"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("from_id", sa.UUID(), nullable=False, comment="Счет списания"),
        sa.Column("to_id", sa.UUID(), nullable=False, comment="Счет зачисления"),
        sa.Column(
            "order_id",
            sa.UUID(),
            nullable=True,
            comment="Заказ, за который прошла оплата (если есть)",
        ),
        sa.Column(
            "verified_by_id",
            sa.UUID(),
            nullable=True,
            comment="Сотрудник (бухгалтер), подтвердивший перевод",
        ),
        sa.Column("amount", sa.BIGINT(), nullable=False, comment="Сумма перевода"),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "REJECTED",
                name="transaction_status_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Статус (PENDING - ожидание, COMPLETED - исполнено, REJECTED - отмена)",
        ),
        sa.Column(
            "reason",
            sa.String(length=255),
            nullable=False,
            comment="Основание/Комментарий (например: 'Оплата картой по заказу #123')",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint("amount > 0", name="ck_transaction_amount_pos"),
        sa.CheckConstraint("from_id != to_id", name="ck_transaction_no_self_transfer"),
        sa.ForeignKeyConstraint(["from_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["to_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["verified_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        comment="Финансовый леджер (Event Sourcing). Строго только добавление (Append-only)",
    )
    op.create_index(
        "idx_transaction_from_status",
        "transactions",
        ["from_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_transaction_to_status", "transactions", ["to_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_order_id"), "transactions", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_verified_by_id"),
        "transactions",
        ["verified_by_id"],
        unique=False,
    )
    op.create_table(
        "stock_transactions",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("transfer_id", sa.UUID(), nullable=False),
        sa.Column("from_id", sa.UUID(), nullable=False),
        sa.Column("to_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity", sa.Integer(), nullable=False, comment="Проведенное количество"
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint(
            "quantity > 0", name="ck_stock_transaction_quantity_positive"
        ),
        sa.ForeignKeyConstraint(["from_id"], ["inventories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["to_id"], ["inventories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["transfer_id", "from_id", "to_id"],
            ["stock_transfers.id", "stock_transfers.from_id", "stock_transfers.to_id"],
            name="fk_stock_transaction_strict_route",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Строгий леджер движения товаров (Event Sourcing). Истина в последней инстанции",
    )
    op.create_index(
        "idx_st_product_from",
        "stock_transactions",
        ["product_id", "from_id"],
        unique=False,
    )
    op.create_index(
        "idx_st_product_to", "stock_transactions", ["product_id", "to_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transactions_from_id"),
        "stock_transactions",
        ["from_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_product_id"),
        "stock_transactions",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_to_id"),
        "stock_transactions",
        ["to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_transfer_id"),
        "stock_transactions",
        ["transfer_id"],
        unique=False,
    )
    op.create_table(
        "stock_transfer_items",
        sa.Column("transfer_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "quantity", sa.Integer(), nullable=False, comment="Количество в документе"
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_stock_transfer_item_quantity_pos"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["transfer_id"], ["stock_transfers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Черновик строк накладной (не влияет на остатки, пока статус DRAFT)",
    )
    op.create_index(
        op.f("ix_stock_transfer_items_product_id"),
        "stock_transfer_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transfer_items_transfer_id"),
        "stock_transfer_items",
        ["transfer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_transfer_items_transfer_id"), table_name="stock_transfer_items"
    )
    op.drop_index(
        op.f("ix_stock_transfer_items_product_id"), table_name="stock_transfer_items"
    )
    op.drop_table("stock_transfer_items")
    op.drop_index(
        op.f("ix_stock_transactions_transfer_id"), table_name="stock_transactions"
    )
    op.drop_index(op.f("ix_stock_transactions_to_id"), table_name="stock_transactions")
    op.drop_index(
        op.f("ix_stock_transactions_product_id"), table_name="stock_transactions"
    )
    op.drop_index(
        op.f("ix_stock_transactions_from_id"), table_name="stock_transactions"
    )
    op.drop_index("idx_st_product_to", table_name="stock_transactions")
    op.drop_index("idx_st_product_from", table_name="stock_transactions")
    op.drop_table("stock_transactions")
    op.drop_index(op.f("ix_transactions_verified_by_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_order_id"), table_name="transactions")
    op.drop_index("idx_transaction_to_status", table_name="transactions")
    op.drop_index("idx_transaction_from_status", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_stock_transfers_type"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_to_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_status"), table_name="stock_transfers")
    op.drop_index(
        op.f("ix_stock_transfers_route_sheet_id"), table_name="stock_transfers"
    )
    op.drop_index(op.f("ix_stock_transfers_order_id"), table_name="stock_transfers")
    op.drop_index(op.f("ix_stock_transfers_from_id"), table_name="stock_transfers")
    op.drop_table("stock_transfers")
    op.drop_index(op.f("ix_order_items_product_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_orders_warehouse_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_sale_type"), table_name="orders")
    op.drop_index(op.f("ix_orders_courier_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_inventory_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(
        op.f("ix_inventory_balances_product_id"), table_name="inventory_balances"
    )
    op.drop_table("inventory_balances")
    op.drop_index(
        "uq_active_courier_inventory",
        table_name="inventories",
        postgresql_where=sa.text("type = 'COURIER' AND is_active = true"),
    )
    op.drop_index(op.f("ix_inventories_type"), table_name="inventories")
    op.drop_index("idx_inventory_user_type", table_name="inventories")
    op.drop_table("inventories")
    op.drop_index(op.f("ix_identities_user_id"), table_name="identities")
    op.drop_table("identities")
    op.drop_index(op.f("ix_accounts_type"), table_name="accounts")
    op.drop_index("idx_account_user_type", table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_products_type"), table_name="products")
    op.drop_index(op.f("ix_products_returnable_item_id"), table_name="products")
    op.drop_index(
        "idx_product_attributes_gin", table_name="products", postgresql_using="gin"
    )
    op.drop_table("products")
    # ### end Alembic commands ###
