"""add_missing_fkey_indexes

Revision ID: cf2a824cf0fb
Revises: e314edc17991
Create Date: 2026-02-25 08:51:16.419293

"""

from collections.abc import Sequence

from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf2a824cf0fb"
down_revision: str | Sequence[str] | None = "e314edc17991"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_order_items_order_id"),
        "order_items",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_items_product_id"),
        "order_items",
        ["product_id"],
        unique=False,
    )
    op.alter_column(
        "orders",
        "payment_method",
        existing_type=postgresql.ENUM(
            "CASH",
            "CARD",
            "CONTRACT",
            name="payment_method_enum",
            metadata=MetaData(),
        ),
        comment="Намерение клиента по оплате: Наличные, Карта",
        existing_comment="Намерение клиента по оплате: Наличные, Карта",
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_orders_client_id"), "orders", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_orders_courier_id"), "orders", ["courier_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_verified_by_id"),
        "transactions",
        ["verified_by_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transactions_verified_by_id"), table_name="transactions"
    )
    op.drop_index(op.f("ix_orders_courier_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_id"), table_name="orders")
    op.alter_column(
        "orders",
        "payment_method",
        existing_type=postgresql.ENUM(
            "CASH",
            "CARD",
            "CONTRACT",
            name="payment_method_enum",
            metadata=MetaData(),
        ),
        comment="Намерение клиента по оплате: Наличные, Карта или Перечисление",
        existing_comment="Намерение клиента по оплате: Наличные, Карта",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_order_items_product_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    # ### end Alembic commands ###
