"""init

Revision ID: e314edc17991
Revises:
Create Date: 2026-02-25 08:34:43.239633

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import MetaData
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e314edc17991"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column(
            "type",
            postgresql.ENUM(
                "WATER",
                "CONTAINER",
                "EQUIPMENT",
                name="product_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("price", sa.INTEGER(), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("returnable_item_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["returnable_item_id"], ["products.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column(
            "username",
            sa.String(length=255),
            nullable=False,
            comment="ФИО или Название компании",
        ),
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM",
                "ADMIN",
                "ACCOUNTANT",
                "STOREKEEPER",
                "CASHIER",
                "COURIER",
                "CLIENT_B2C",
                "CLIENT_B2B",
                name="user_role_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column(
            "type",
            sa.Enum(
                "REVENUE",
                "CASH",
                "CARD",
                "BANK",
                "DISCOUNT",
                "CLIENT",
                "COURIER",
                name="account_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("balance", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accounts_type"), "accounts", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False
    )
    op.create_table(
        "identities",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "LOCAL",
                "GOOGLE",
                "TELEGRAM",
                "APPLE",
                name="auth_provider_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column(
            "provider_identity_id", sa.String(length=255), nullable=False
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider",
            "provider_identity_id",
            name="uq_identities_provider_identity_id",
        ),
    )
    op.create_index(
        op.f("ix_identities_provider_identity_id"),
        "identities",
        ["provider_identity_id"],
        unique=False,
    )
    op.create_table(
        "inventories",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="Кто материально ответственен за эту точку?",
        ),
        sa.Column(
            "type",
            sa.Enum(
                "FACTORY",
                "WAREHOUSE",
                "COURIER_CAR",
                "CLIENT_BALCONY",
                "VIRTUAL",
                "LOSS",
                name="inventory_type_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.VARCHAR(length=255),
            nullable=False,
            comment="Например: 'Склад №1', 'Машина Дамас 01A123BC'",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventories_type"), "inventories", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_inventories_user_id"),
        "inventories",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("courier_id", sa.UUID(), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "CASH",
                "CARD",
                "CONTRACT",
                name="payment_method_enum",
                metadata=MetaData(),
            ),
            nullable=False,
            comment="Намерение клиента по оплате: Наличные, Карта или Перечисление",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "ASSIGNED",
                "IN_TRANSIT",
                "ARRIVED",
                "DELIVERED",
                "CANCELLED",
                name="order_status_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column(
            "total_amount",
            sa.INTEGER(),
            nullable=False,
            comment="Сумма всего заказа",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["courier_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column(
            "unit_price",
            sa.INTEGER(),
            nullable=False,
            comment="Цена за 1 шт на момент оформления",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("from_id", sa.UUID(), nullable=False),
        sa.Column("to_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.BIGINT(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "REJECTED",
                name="transaction_status_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("verified_by_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.VARCHAR(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint(
            "amount > 0", name="check_transaction_amount_positive"
        ),
        sa.CheckConstraint("from_id != to_id", name="check_no_self_transfer"),
        sa.ForeignKeyConstraint(
            ["from_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["to_id"], ["accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transaction_from_status",
        "transactions",
        ["from_id", "status"],
        unique=False,
    )
    op.create_index(
        "idx_transaction_to_status",
        "transactions",
        ["to_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_from_id"),
        "transactions",
        ["from_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_order_id"),
        "transactions",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_status"),
        "transactions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_to_id"), "transactions", ["to_id"], unique=False
    )
    op.create_table(
        "transfers",
        sa.Column("number", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("from_inventory_id", sa.UUID(), nullable=False),
        sa.Column("to_inventory_id", sa.UUID(), nullable=False),
        sa.Column("initiator_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "COMPLETED",
                "CANCELLED",
                name="transfer_status_enum",
                metadata=MetaData(),
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint(
            "from_inventory_id != to_inventory_id",
            name="check_transfer_different_inventories",
        ),
        sa.ForeignKeyConstraint(
            ["from_inventory_id"], ["inventories.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["initiator_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["to_inventory_id"], ["inventories.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transfers_from_inventory_id"),
        "transfers",
        ["from_inventory_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transfers_number"), "transfers", ["number"], unique=True
    )
    op.create_index(
        op.f("ix_transfers_status"), "transfers", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_transfers_to_inventory_id"),
        "transfers",
        ["to_inventory_id"],
        unique=False,
    )
    op.create_table(
        "stock_transactions",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("from_id", sa.UUID(), nullable=False),
        sa.Column("to_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("transfer_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.CheckConstraint(
            "(order_id IS NULL) OR (transfer_id IS NULL)",
            name="ck_stock_transaction_exclusive_document",
        ),
        sa.CheckConstraint(
            "from_id != to_id", name="ck_stock_transaction_no_circular"
        ),
        sa.CheckConstraint(
            "quantity > 0", name="ck_stock_transaction_quantity_positive"
        ),
        sa.ForeignKeyConstraint(
            ["from_id"], ["inventories.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["to_id"], ["inventories.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"], ["transfers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_st_product_from",
        "stock_transactions",
        ["product_id", "from_id"],
        unique=False,
    )
    op.create_index(
        "idx_st_product_to",
        "stock_transactions",
        ["product_id", "to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_from_id"),
        "stock_transactions",
        ["from_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_order_id"),
        "stock_transactions",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_product_id"),
        "stock_transactions",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_to_id"),
        "stock_transactions",
        ["to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_transactions_transfer_id"),
        "stock_transactions",
        ["transfer_id"],
        unique=False,
    )
    op.create_table(
        "transfer_items",
        sa.Column("transfer_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False, comment="ID (UUIDv7)"),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            nullable=False,
            comment="Флаг активности записи. False означает логическое удаление.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"], ["transfers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transfer_product_unique",
        "transfer_items",
        ["transfer_id", "product_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_transfer_items_transfer_id"),
        "transfer_items",
        ["transfer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transfer_items_transfer_id"), table_name="transfer_items"
    )
    op.drop_index("idx_transfer_product_unique", table_name="transfer_items")
    op.drop_table("transfer_items")
    op.drop_index(
        op.f("ix_stock_transactions_transfer_id"),
        table_name="stock_transactions",
    )
    op.drop_index(
        op.f("ix_stock_transactions_to_id"), table_name="stock_transactions"
    )
    op.drop_index(
        op.f("ix_stock_transactions_product_id"),
        table_name="stock_transactions",
    )
    op.drop_index(
        op.f("ix_stock_transactions_order_id"), table_name="stock_transactions"
    )
    op.drop_index(
        op.f("ix_stock_transactions_from_id"), table_name="stock_transactions"
    )
    op.drop_index("idx_st_product_to", table_name="stock_transactions")
    op.drop_index("idx_st_product_from", table_name="stock_transactions")
    op.drop_table("stock_transactions")
    op.drop_index(op.f("ix_transfers_to_inventory_id"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_status"), table_name="transfers")
    op.drop_index(op.f("ix_transfers_number"), table_name="transfers")
    op.drop_index(
        op.f("ix_transfers_from_inventory_id"), table_name="transfers"
    )
    op.drop_table("transfers")
    op.drop_index(op.f("ix_transactions_to_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_order_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_from_id"), table_name="transactions")
    op.drop_index("idx_transaction_to_status", table_name="transactions")
    op.drop_index("idx_transaction_from_status", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_index(op.f("ix_inventories_user_id"), table_name="inventories")
    op.drop_index(op.f("ix_inventories_type"), table_name="inventories")
    op.drop_table("inventories")
    op.drop_index(
        op.f("ix_identities_provider_identity_id"), table_name="identities"
    )
    op.drop_table("identities")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_type"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("products")
    # Вручную подчищаем ENUM типы
    sa.Enum(name="user_role_enum").drop(op.get_bind())
    sa.Enum(name="product_type_enum").drop(op.get_bind())
    sa.Enum(name="account_type_enum").drop(op.get_bind())
    sa.Enum(name="auth_provider_enum").drop(op.get_bind())
    sa.Enum(name="inventory_type_enum").drop(op.get_bind())
    sa.Enum(name="payment_method_enum").drop(op.get_bind())
    sa.Enum(name="order_status_enum").drop(op.get_bind())
    sa.Enum(name="transaction_status_enum").drop(op.get_bind())
    sa.Enum(name="transfer_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
